server:
  port: 8001
  
spring:
  application:
    name: eureka-dept-provider
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    #以{cipher}开头，spring cloud config会把面的内容进行解密
    #password: {cipher}7e2ba34842bade307ef3aa21b383f6c2bd18703cb4e8383ee9090dd773e4a965
    password: mysqlAdmin
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:7001/eureka/  #与注册中心的defaultZone对应
      defaultZone: http://registry7001:7001/eureka/
  instance:
    instance-id: dept-provider-8001  
    prefer-ip-address: true
    
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #指定mapper.xml文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml  #指定mybatis全局配置文件所在路径